# Generated by Django 3.1.2 on 2023-11-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=50)),
                ('capacidad', models.IntegerField(max_length=50)),
            ],
        ),
    ]
