# Generated by Django 3.1.2 on 2023-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(max_length=20),
        ),
    ]
