# Generated by Django 3.1.2 on 2023-11-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231124_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(),
        ),
    ]
