# Generated by Django 3.1.2 on 2023-11-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231124_1844'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sala',
            table='Sala',
        ),
    ]
