# Generated by Django 3.1.2 on 2023-11-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231124_1847'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sala',
            table='sala',
        ),
    ]
