# Generated by Django 3.1.2 on 2023-11-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231124_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horas', models.IntegerField()),
            ],
            options={
                'db_table': 'taller',
            },
        ),
    ]
