# Generated by Django 3.1.2 on 2023-11-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taller_sala'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sala',
            table=None,
        ),
    ]
