# Generated by Django 3.1.2 on 2023-11-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231124_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='sala',
        ),
        migrations.AlterModelTable(
            name='taller',
            table=None,
        ),
    ]
