# Generated by Django 3.1.2 on 2023-11-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_taller_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
