# Generated by Django 3.1.2 on 2023-11-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20231124_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
