# Generated by Django 3.1.2 on 2023-11-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_taller_municipalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('nombre_apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_ins', models.CharField(max_length=50)),
            ],
        ),
    ]
