# Generated by Django 3.1.2 on 2023-11-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
            preserve_default=False,
        ),
    ]
