# Generated by Django 3.1.2 on 2023-11-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='inscripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inscripcion'),
            preserve_default=False,
        ),
    ]
