# Generated by Django 3.1.2 on 2023-11-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_taller_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inicio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_termino',
            field=models.CharField(max_length=50),
        ),
    ]
