# Generated by Django 3.1.2 on 2023-11-27 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='inscripcion',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='taller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.taller'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='cupos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
