# Generated by Django 3.1.2 on 2023-11-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20231126_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='taller',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='usuario',
        ),
    ]
