# Generated by Django 3.1.2 on 2023-11-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20231126_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
